---
apiVersion: v1
kind: Service
metadata:
  name: storageos-api
spec:
  ports:
  - port: 5705
    targetPort: 5705
    name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Endpoints
apiVersion: v1
metadata:
  name: storageos-api
subsets:
  - addresses:
      - ip: 10.154.0.2
      - ip: 10.154.0.3
      - ip: 10.154.0.4
    ports:
      - port: 5705
        name: http
