apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  labels:
    cluster: demo-storageos-node
    region: europe-west2-a
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

